// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZsp4BWKcC9Hm0iqpR_MWjPVNsNjpz7s4',
    appId: '1:153996966068:web:884cd8bc7d1c5f480bbfe1',
    messagingSenderId: '153996966068',
    projectId: 'corejourney-dev',
    authDomain: 'corejourney-dev.firebaseapp.com',
    storageBucket: 'corejourney-dev.firebasestorage.app',
    measurementId: 'G-RT8WC36DCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE2vmkwjVR6aTgvE_fZ7P6WUj1Ta97_s8',
    appId: '1:153996966068:android:9a0abcc75c8e6f7e0bbfe1',
    messagingSenderId: '153996966068',
    projectId: 'corejourney-dev',
    storageBucket: 'corejourney-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYFo0u_3L9QJK3NxSd241w-Zer8lqVDEY',
    appId: '1:153996966068:ios:2106fb17d0bed5700bbfe1',
    messagingSenderId: '153996966068',
    projectId: 'corejourney-dev',
    storageBucket: 'corejourney-dev.firebasestorage.app',
    iosBundleId: 'com.alexandermessinger.corejourney',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYFo0u_3L9QJK3NxSd241w-Zer8lqVDEY',
    appId: '1:153996966068:ios:c05a136bf8b3bc320bbfe1',
    messagingSenderId: '153996966068',
    projectId: 'corejourney-dev',
    storageBucket: 'corejourney-dev.firebasestorage.app',
    iosBundleId: 'com.example.corejourney',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZsp4BWKcC9Hm0iqpR_MWjPVNsNjpz7s4',
    appId: '1:153996966068:web:9dc25e714e53958a0bbfe1',
    messagingSenderId: '153996966068',
    projectId: 'corejourney-dev',
    authDomain: 'corejourney-dev.firebaseapp.com',
    storageBucket: 'corejourney-dev.firebasestorage.app',
    measurementId: 'G-1B7LHHB9B1',
  );
}
