// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhyhMSeKeohmJfbKus6qWgX10_SZiwr-Q',
    appId: '1:673501917704:android:63ddd42b1717d282e657bd',
    messagingSenderId: '673501917704',
    projectId: 'corejourney-prod',
    storageBucket: 'corejourney-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK9_s9KUMTSG3p9NOKebWRenxjjbuKPeU',
    appId: '1:673501917704:ios:9446cd7e1a342713e657bd',
    messagingSenderId: '673501917704',
    projectId: 'corejourney-prod',
    storageBucket: 'corejourney-prod.firebasestorage.app',
    iosBundleId: 'com.alexandermessinger.corejourney',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE74p_YgOIRMQV5T9DhZWrYsuuwPJz5Q0',
    appId: '1:673501917704:web:1fd84a6ac991312de657bd',
    messagingSenderId: '673501917704',
    projectId: 'corejourney-prod',
    authDomain: 'corejourney-prod.firebaseapp.com',
    storageBucket: 'corejourney-prod.firebasestorage.app',
    measurementId: 'G-KDCMXZY7K7',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAK9_s9KUMTSG3p9NOKebWRenxjjbuKPeU',
    appId: '1:673501917704:ios:669e646fb9018d4ee657bd',
    messagingSenderId: '673501917704',
    projectId: 'corejourney-prod',
    storageBucket: 'corejourney-prod.firebasestorage.app',
    iosBundleId: 'com.example.corejourney',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE74p_YgOIRMQV5T9DhZWrYsuuwPJz5Q0',
    appId: '1:673501917704:web:f1416578131ee8bfe657bd',
    messagingSenderId: '673501917704',
    projectId: 'corejourney-prod',
    authDomain: 'corejourney-prod.firebaseapp.com',
    storageBucket: 'corejourney-prod.firebasestorage.app',
    measurementId: 'G-N0BQYXJ69M',
  );

}