import 'reflex_questionnaire.dart';

final childParentQuestionnaireV1 = ReflexQuestionnaireDefinition(
  id: 'child_parent_reflex_profile',
  version: 'child_parent_v1_2026_05',
  type: ReflexQuestionnaireType.childParentReport,
  title: 'Reflexprofil für Kinder',
  scoring: const ReflexScoringDefinition(
    strongPercent: 100,
    elevatedPercent: 80,
    indicationPercent: 50,
  ),
  questions: [
    _q(1, ReflexQuestionModule.pregnancyBirth,
        'Gab es während der Schwangerschaft gesundheitliche Probleme?',
        reflexes: [r.delay, r.flr, r.moro]),
    const ReflexQuestion(
      id: 'q002_pregnancy_health_problem_details',
      number: 2,
      module: ReflexQuestionModule.pregnancyBirth,
      text:
          'Welche gesundheitlichen Probleme gab es während der Schwangerschaft?',
      answerType: ReflexAnswerType.multiSelectWithText,
      role: ReflexQuestionRole.context,
      followUpOf: 'q001',
      options: [
        ReflexQuestionOption(
          id: 'preeclampsia',
          label: 'Schwangerschaftsvergiftung',
          adminMetricId: 'pregnancy_preeclampsia',
        ),
        ReflexQuestionOption(
          id: 'bleeding',
          label: 'Schwangerschaftsblutung',
          adminMetricId: 'pregnancy_bleeding',
        ),
        ReflexQuestionOption(
          id: 'hypertension',
          label: 'Bluthochdruck',
          adminMetricId: 'pregnancy_hypertension',
        ),
      ],
    ),
    _q(3, ReflexQuestionModule.pregnancyBirth,
        'Gab es während der Schwangerschaft besondere persönliche Belastungen oder starken Stress?',
        reflexes: [r.delay, r.flr, r.moro]),
    _q(4, ReflexQuestionModule.pregnancyBirth,
        'Musstest du während der Schwangerschaft lange liegen?',
        reflexes: [r.delay]),
    _context(5, ReflexQuestionModule.pregnancyBirth,
        'Gab es Schwierigkeiten bei der Geburt?'),
    const ReflexQuestion(
      id: 'q006',
      number: 6,
      module: ReflexQuestionModule.pregnancyBirth,
      text: 'Wurden Geburtshilfe-Instrumente eingesetzt?',
      answerType: ReflexAnswerType.multiSelectWithText,
      role: ReflexQuestionRole.context,
      followUpOf: 'q005',
      options: [
        ReflexQuestionOption(
          id: 'forceps',
          label: 'Geburtszange',
          adminMetricId: 'birth_forceps',
        ),
        ReflexQuestionOption(
          id: 'vacuum',
          label: 'Saugglocke',
          adminMetricId: 'birth_vacuum',
        ),
      ],
    ),
    _context(8, ReflexQuestionModule.pregnancyBirth, 'Nabelschnur um den Hals',
        followUpOf: 'q005'),
    _context(9, ReflexQuestionModule.pregnancyBirth, 'Sonstiges zur Geburt',
        answerType: ReflexAnswerType.freeText, followUpOf: 'q005'),
    _context(10, ReflexQuestionModule.pregnancyBirth,
        'Lag dein Kind bei der Geburt in Beckenendlage?'),
    _q(11, ReflexQuestionModule.pregnancyBirth,
        'Wurde dein Kind zu früh geboren? (z. B. Frühchen)',
        reflexes: [r.delay]),
    const ReflexQuestion(
      id: 'q011_premature_month',
      number: 11,
      module: ReflexQuestionModule.pregnancyBirth,
      text: 'In welchem Schwangerschaftsmonat wurde dein Kind geboren?',
      answerType: ReflexAnswerType.monthsNumber,
      role: ReflexQuestionRole.context,
      followUpOf: 'q011',
    ),
    _q(12, ReflexQuestionModule.pregnancyBirth,
        'Gab es einen Notkaiserschnitt?',
        reflexes: [r.spinalGalant, r.atnr]),
    _q(13, ReflexQuestionModule.pregnancyBirth,
        'Wurde dein Kind durch einen geplanten Kaiserschnitt geboren?',
        reflexes: [r.spinalGalant, r.atnr]),
    _q(14, ReflexQuestionModule.pregnancyBirth,
        'War der Geburtsvorgang ungewöhnlich kurz? (z. B. Sturzgeburt)',
        reflexes: [r.spinalGalant, r.atnr, r.stnr]),
    _q(15, ReflexQuestionModule.pregnancyBirth,
        'War der Geburtsvorgang ungewöhnlich lang?',
        reflexes: [r.atnr, r.stnr]),
    _q(16, ReflexQuestionModule.pregnancyBirth,
        'Gab es während der Geburt wehenfördernde Maßnahmen?',
        reflexes: [r.spinalGalant, r.atnr, r.stnr]),
    _q(17, ReflexQuestionModule.pregnancyBirth,
        'Bekamst du während der Geburt wehenhemmende Medikamente?',
        reflexes: [r.flr, r.moro, r.spinalGalant, r.atnr, r.stnr]),
    _q(18, ReflexQuestionModule.posturePerception,
        'Lag dein Kind in den ersten Monaten überwiegend auf dem Rücken?',
        reflexes: [r.landau]),
    _q(19, ReflexQuestionModule.posturePerception,
        'Steht dein Kind oft mit nach innen gedrehten Füßen da?',
        reflexes: [r.flr, r.babinski]),
    _q(20, ReflexQuestionModule.posturePerception,
        'Leidet dein Kind unter Nackenverspannungen?',
        reflexes: [r.tlr, r.landau, r.babkin]),
    _q(21, ReflexQuestionModule.posturePerception,
        'Wenn sich dein Kind in Bauchlage auf die Unterarme stützt, den Oberkörper und Kopf anhebt, faustet es dann die Hände?',
        reflexes: [r.babkin, r.palmar, r.righting]),
    _q(22, ReflexQuestionModule.posturePerception,
        'Rollt dein Kind die Zehen immer wieder ein?',
        reflexes: [r.plantar]),
    _q(23, ReflexQuestionModule.posturePerception,
        'Kann dein Kind mindestens 10 Sekunden auf einem Bein stehen?',
        reflexes: [r.tlr, r.atnr]),
    _q(24, ReflexQuestionModule.posturePerception,
        'Kann dein Kind mindestens 10 Sekunden mit geschlossenen Augen auf einem Bein stehen?',
        reflexes: [r.tlr, r.atnr]),
    _q(25, ReflexQuestionModule.posturePerception,
        'Sitzt dein Kind gerne auf einem oder beiden Füßen?',
        reflexes: [r.stnr]),
    _q(26, ReflexQuestionModule.posturePerception,
        'Schlingt dein Kind beim Sitzen seine Beine um die Stuhlbeine?',
        reflexes: [r.stnr]),
    _q(27, ReflexQuestionModule.posturePerception,
        'Neigt dein Kind den Kopf oft nach unten, der Blick geht aber von unten nach oben? (Misstrauischer Blick)',
        reflexes: [r.stnr],
        helpText:
            'Gemeint ist die beobachtbare Kopf- und Blickhaltung, nicht eine Bewertung des Verhaltens.'),
    _q(28, ReflexQuestionModule.posturePerception,
        'Hat dein Kind den Kopf oft nach oben geneigt und schaut dabei von oben herab? (Hochnäsiger Blick)',
        reflexes: [r.stnr],
        helpText:
            'Gemeint ist die beobachtbare Kopf- und Blickhaltung, nicht eine Bewertung des Verhaltens.'),
    _q(29, ReflexQuestionModule.posturePerception,
        'Hat dein Kind Schwierigkeiten, über längere Zeit still zu sitzen?',
        reflexes: [r.spinalGalant, r.stnr]),
    _q(30, ReflexQuestionModule.posturePerception,
        'Lehnt sich dein Kind kaum oder selten an der Stuhllehne an?',
        reflexes: [r.spinalGalant]),
    _q(31, ReflexQuestionModule.posturePerception,
        'Ist dein Kind übermäßig kitzelig an den Füßen?',
        reflexes: [r.babinski]),
    _q(32, ReflexQuestionModule.posturePerception,
        'Ist dein Kind übermäßig kitzelig am Körper?',
        reflexes: [r.spinalGalant]),
    _q(33, ReflexQuestionModule.posturePerception, 'Hat dein Kind X-Beine?',
        reflexes: [r.babinski]),
    _q(34, ReflexQuestionModule.posturePerception, 'Hat dein Kind O-Beine?',
        reflexes: [r.babinski]),
    _q(35, ReflexQuestionModule.motorSkills,
        'Hat dein Kind das Krabbeln ausgelassen?',
        reflexes: [r.stnr]),
    _context(36, ReflexQuestionModule.motorSkills,
        'Wenn nein, ab wann ist dein Kind gekrabbelt?',
        answerType: ReflexAnswerType.monthsNumber, followUpOf: 'q035'),
    _context(37, ReflexQuestionModule.motorSkills,
        'Wann ist dein Kind das erste Mal gelaufen?',
        answerType: ReflexAnswerType.monthsNumber),
    _q(38, ReflexQuestionModule.motorSkills,
        'Neigt dein Kind dazu, auf den Zehenspitzen zu gehen?',
        reflexes: [r.tlr, r.stnr, r.landau, r.plantar]),
    _q(39, ReflexQuestionModule.motorSkills,
        'Hat dein Kind einen schiefen Gang?',
        reflexes: [r.spinalGalant]),
    _q(40, ReflexQuestionModule.motorSkills,
        'Fällt es deinem Kind schwer, eine feste Faust zu machen?',
        reflexes: [r.babkin]),
    _q(41, ReflexQuestionModule.motorSkills,
        'Zieht dein Kind Strümpfe und Schuhe umständlich an?',
        reflexes: [r.plantar]),
    _q(42, ReflexQuestionModule.motorSkills,
        'Stützt dein Kind beim Sitzen am Tisch häufig den Kopf mit einem oder beiden Armen ab?',
        reflexes: [r.tlr, r.stnr, r.landau]),
    _q(43, ReflexQuestionModule.motorSkills,
        'Räkelt und streckt sich dein Kind häufig beim Sitzen (Kopf nach hinten, Beine nach vorne)?',
        reflexes: [r.stnr]),
    _q(44, ReflexQuestionModule.motorSkills,
        'Hat dein Kind Probleme, einen Ball zu fangen?',
        reflexes: [r.moro, r.tlr, r.stnr]),
    _q(45, ReflexQuestionModule.motorSkills,
        'Hat oder hatte dein Kind Probleme beim Schwimmenlernen, vor allem beim Brustschwimmen?',
        reflexes: [r.stnr, r.landau]),
    _q(46, ReflexQuestionModule.motorSkills,
        'Kann sich dein Kind schlecht oder gar nicht orientieren?',
        reflexes: [r.tlr, r.atnr]),
    _q(47, ReflexQuestionModule.behaviorEmotion,
        'War dein Kind in den ersten Monaten ein Schreikind?',
        reflexes: [r.flr, r.moro, r.landau]),
    _q(48, ReflexQuestionModule.behaviorEmotion,
        'Ist dein Kind sehr empfindlich auf Geräusche?',
        reflexes: [r.flr, r.moro]),
    _q(49, ReflexQuestionModule.behaviorEmotion,
        'Ist dein Kind sehr empfindlich auf Licht oder Helligkeit?',
        reflexes: [r.flr, r.moro]),
    _q(50, ReflexQuestionModule.behaviorEmotion,
        'Ist dein Kind sehr empfindlich auf Berührung?',
        reflexes: [r.flr, r.moro]),
    _q(51, ReflexQuestionModule.behaviorEmotion,
        'Ist dein Kind überdurchschnittlich ängstlich?',
        reflexes: [r.flr, r.moro]),
    _q(52, ReflexQuestionModule.behaviorEmotion,
        'Leidet dein Kind unter Trennungsangst?',
        reflexes: [r.flr, r.moro]),
    _q(53, ReflexQuestionModule.behaviorEmotion,
        'Ist dein Kind oft weinerlich?',
        reflexes: [r.moro]),
    _q(54, ReflexQuestionModule.behaviorEmotion,
        'Ist dein Kind leicht reizbar bzw. schnell wütend?',
        reflexes: [r.moro, r.atnr]),
    _q(55, ReflexQuestionModule.behaviorEmotion,
        'Wirkt dein Kind oft unorganisiert?',
        reflexes: [r.spinalGalant]),
    _q(56, ReflexQuestionModule.behaviorEmotion,
        'Ist dein Kind oft vergesslich?',
        reflexes: [r.spinalGalant]),
    _q(57, ReflexQuestionModule.behaviorEmotion, 'Liebt dein Kind Routine?',
        reflexes: [r.moro]),
    _q(58, ReflexQuestionModule.behaviorEmotion,
        'Ist dein Kind gerne in einer Fantasiewelt?',
        reflexes: [r.moro],
        helpText:
            'Gemeint ist nicht normales Fantasiespiel, sondern ein starkes Zurückziehen in Fantasie oder Tagträume, wenn dadurch Alltagssituationen schwerer gelingen.'),
    _q(59, ReflexQuestionModule.behaviorEmotion,
        'Steht sich dein Kind häufig selbst im Weg?',
        reflexes: [r.moro],
        helpText:
            'Gemeint ist z. B., dass dein Kind bei bekannten Aufgaben blockiert wirkt, sich schwer organisiert, vermeidet oder durch Unsicherheit, Frust oder Durcheinander ausgebremst wird.'),
    _q(60, ReflexQuestionModule.behaviorEmotion,
        'Ist dein Kind leicht ablenkbar?',
        reflexes: [r.moro]),
    _q(61, ReflexQuestionModule.behaviorEmotion,
        'Wurde bei deinem Kind ADHS/ADS diagnostiziert oder befindet sich dies in Abklärung?',
        reflexes: [r.flr, r.moro, r.spinalGalant, r.tlr, r.landau, r.babinski],
        trainerFlagLabel: 'ADHS / ADS diagnostiziert oder in Abklärung'),
    _context(62, ReflexQuestionModule.behaviorEmotion,
        'Hat dein Kind ein erhöhtes Schmerzempfinden?'),
    _context(63, ReflexQuestionModule.behaviorEmotion,
        'Hat dein Kind ein geringes Schmerzempfinden?'),
    _q(64, ReflexQuestionModule.speech,
        'Trägt oder trug dein Kind eine Zahnspange?',
        reflexes: [r.babkin, r.rootingSucking]),
    _q(65, ReflexQuestionModule.speech,
        'Hat dein Kind eine deutliche Zahnfehlstellung oder einen gotischen Gaumen?',
        reflexes: [r.babkin, r.rootingSucking]),
    _q(66, ReflexQuestionModule.speech, 'Knirscht dein Kind mit den Zähnen?',
        reflexes: [r.babkin]),
    _q(67, ReflexQuestionModule.speech,
        'Hat dein Kind sehr lange am Daumen gelutscht oder einen Schnuller gehabt?',
        reflexes: [r.babkin, r.rootingSucking]),
    _q(68, ReflexQuestionModule.speech,
        'Hat dein Kind einen übermäßig starken Speichelfluss?',
        reflexes: [r.babkin, r.rootingSucking]),
    _q(69, ReflexQuestionModule.speech,
        'Macht dein Kind beim Schreiben oder Malen Mundbewegungen?',
        reflexes: [r.babkin, r.plantar, r.palmar]),
    _q(70, ReflexQuestionModule.speech,
        'Beißt dein Kind oft die Zähne fest zusammen, besonders wenn es sich konzentriert?',
        reflexes: [r.babkin, r.plantar, r.palmar]),
    _q(71, ReflexQuestionModule.speech,
        'Spricht dein Kind eher undeutlich (z. B. Nuscheln, falsche Aussprache von Lauten)?',
        reflexes: [r.stnr, r.babkin, r.plantar, r.palmar]),
    _q(72, ReflexQuestionModule.speech,
        'Neigt dein Kind zur Schwatzhaftigkeit bzw. redet es unablässig?',
        reflexes: [r.spinalGalant]),
    _q(73, ReflexQuestionModule.drawingWriting,
        'Hält dein Kind den Stift verkrampft?',
        reflexes: [r.babkin, r.palmar]),
    _q(74, ReflexQuestionModule.drawingWriting,
        'Hält dein Kind den Stift beim Malen oder Schreiben in einer Faust?',
        reflexes: [r.babkin, r.palmar]),
    _q(75, ReflexQuestionModule.drawingWriting,
        'Drückt dein Kind den Stift beim Schreiben oder Malen sehr stark auf?',
        reflexes: [r.palmar]),
    _q(76, ReflexQuestionModule.drawingWriting,
        'Hat dein Kind wenig Lust zu malen oder zu schreiben?',
        reflexes: [r.stnr, r.palmar, r.righting]),
    _q(77, ReflexQuestionModule.drawingWriting,
        'Ermüdet dein Kind sehr schnell beim Malen oder Schreiben?',
        reflexes: [r.stnr, r.palmar, r.righting]),
    _q(78, ReflexQuestionModule.drawingWriting,
        'Verdreht dein Kind Buchstaben, wie zum Beispiel b und d?',
        reflexes: [r.tlr, r.stnr]),
    _q(79, ReflexQuestionModule.drawingWriting,
        'Schreibt dein Kind in Spiegelschrift?',
        reflexes: [r.tlr, r.stnr]),
    _q(80, ReflexQuestionModule.drawingWriting,
        'Hat dein Kind ein gutes mündliches Wissen, kann es aber nicht aufs Papier bringen?',
        reflexes: [r.stnr, r.babkin]),
    _q(81, ReflexQuestionModule.drawingWriting,
        'Hat dein Kind eine unleserliche Schrift, vor allem bei der Schreibschrift?',
        reflexes: [r.stnr, r.babkin]),
    _q(82, ReflexQuestionModule.drawingWriting,
        'Legt dein Kind beim Malen oder Schreiben das Blatt im 90-Grad-Winkel vor sich?',
        reflexes: [r.atnr]),
    _q(83, ReflexQuestionModule.drawingWriting,
        'Fällt es deinem Kind schwer, die Linien beim Schreiben einzuhalten?',
        reflexes: [r.atnr]),
    _q(84, ReflexQuestionModule.school,
        'Hat dein Kind Angst vor der Schule (Bauchschmerzen, Übelkeit etc.)?',
        reflexes: [r.flr, r.moro]),
    _q(85, ReflexQuestionModule.school,
        'Hat dein Kind Schwierigkeiten, von der Tafel abzuschreiben (langsam, anstrengend etc.)?',
        reflexes: [r.tlr]),
    _q(86, ReflexQuestionModule.school, 'Arbeitet dein Kind eher zu langsam?',
        reflexes: [r.tlr]),
    _q(87, ReflexQuestionModule.school,
        'Hat dein Kind Schwierigkeiten in der Rechtschreibung?',
        reflexes: [r.tlr, r.atnr, r.stnr]),
    _q(88, ReflexQuestionModule.school,
        'Hat dein Kind Schwierigkeiten in der Grammatik?',
        reflexes: [r.tlr, r.atnr, r.stnr]),
    _q(89, ReflexQuestionModule.school,
        'Hat dein Kind Schwierigkeiten im Rechnen?',
        reflexes: [r.tlr, r.atnr, r.stnr]),
    _q(90, ReflexQuestionModule.school,
        'Hat dein Kind Schwierigkeiten bei Diktaten?',
        reflexes: [r.flr, r.stnr]),
    _q(91, ReflexQuestionModule.school,
        'Hat dein Kind eine Lese-Rechtschreibschwäche?',
        reflexes: [
          r.flr,
          r.moro,
          r.tlr,
          r.atnr,
          r.stnr,
          r.babkin,
          r.plantar,
          r.palmar,
          r.righting,
          r.rootingSucking
        ]),
    _q(92, ReflexQuestionModule.school, 'Hat dein Kind Dyskalkulie?',
        helpText:
            'Dyskalkulie ist eine Rechenschwäche, bei der das Verstehen von Zahlen und mathematischen Zusammenhängen trotz normaler Intelligenz dauerhaft schwerfällt. Im Alltag zeigt sich das z. B. durch: Schwierigkeiten beim Wechselgeld zählen, Uhr lesen, Zahlen merken, Mengen schätzen oder bei einfachen Rechenaufgaben immer wieder neu anfangen müssen.',
        reflexes: [
          r.flr,
          r.moro,
          r.tlr,
          r.atnr,
          r.stnr,
          r.babkin,
          r.plantar,
          r.palmar,
          r.righting,
          r.rootingSucking
        ]),
    _q(93, ReflexQuestionModule.school,
        'Lässt dein Kind beim Lesen oft Buchstaben oder Wörter aus?',
        reflexes: [r.flr, r.stnr]),
    _q(94, ReflexQuestionModule.school,
        'Ermüdet dein Kind schnell beim Lesen?',
        reflexes: [r.flr, r.moro, r.stnr]),
    _q(95, ReflexQuestionModule.school,
        'Hat dein Kind Leseschwierigkeiten (z. B. zu langsam, Wörter auslassen etc.)?',
        reflexes: [r.flr, r.atnr, r.stnr]),
    _q(96, ReflexQuestionModule.school,
        'Kann dein Kind gut vorlesen, weiß aber nicht, was es vorgelesen hat?',
        reflexes: [r.flr, r.atnr]),
    _q(97, ReflexQuestionModule.school, 'Hat dein Kind Lernschwierigkeiten?',
        reflexes: [
          r.flr,
          r.moro,
          r.spinalGalant,
          r.tlr,
          r.atnr,
          r.stnr,
          r.landau,
          r.babinski,
          r.babkin,
          r.plantar,
          r.palmar,
          r.righting,
          r.rootingSucking
        ]),
    _q(98, ReflexQuestionModule.school,
        'Kann sich dein Kind schlecht konzentrieren?',
        reflexes: [r.flr, r.moro]),
    _q(99, ReflexQuestionModule.other,
        'Fragt dein Kind oft nach oder sagt oft "was"?',
        reflexes: [r.tlr, r.atnr, r.stnr]),
    _q(100, ReflexQuestionModule.other,
        'Wird deinem Kind beim Auto- oder Zugfahren schlecht (Reiseübelkeit)?',
        reflexes: [r.flr, r.moro, r.tlr]),
    _q(101, ReflexQuestionModule.other,
        'Hat dein Kind mit 5 Jahren oder später noch nachts eingenässt?',
        reflexes: [r.spinalGalant]),
    _q(102, ReflexQuestionModule.other,
        'Hat dein Kind mit 5 Jahren oder später noch tagsüber eingenässt?',
        reflexes: [r.spinalGalant]),
    _q(103, ReflexQuestionModule.other, 'Mag dein Kind keine enge Kleidung?',
        reflexes: [r.spinalGalant]),
    _q(104, ReflexQuestionModule.other, 'Trägt dein Kind eine Brille?',
        reflexes: [r.flr, r.tlr, r.atnr]),
    _q(105, ReflexQuestionModule.other,
        'Hat dein Kind ein schlechtes Zeitgefühl?',
        reflexes: [r.tlr]),
    _q(106, ReflexQuestionModule.other, 'Leidet dein Kind an Asthma?',
        reflexes: [r.flr, r.moro]),
    _q(107, ReflexQuestionModule.other, 'Leidet dein Kind an Allergien?',
        reflexes: [r.flr, r.moro]),
    _q(108, ReflexQuestionModule.other,
        'Leidet dein Kind an häufigen Infekten?',
        reflexes: [r.flr, r.moro]),
    _warning(109, 'Hat dein Kind Epilepsie?', 'Epilepsie'),
    _warning(
        110,
        'Wurde bei deinem Kind eine Autismus-Spektrum-Diagnose gestellt oder befindet sich dies in Abklärung?',
        'Autismus-Spektrum-Diagnose',
        reflexes: [r.flr]),
    _warning(111, 'Hat dein Kind Trisomie 21 (Downsyndrom)?',
        'Trisomie 21 / Downsyndrom'),
    _warning(
        112,
        'Ist dein Kind in psychologischer oder psychiatrischer Behandlung?',
        'Psychologische / psychiatrische Behandlung',
        reflexes: [r.flr]),
  ],
);

final demoChildShortQuestionnaireV1 = ReflexQuestionnaireDefinition(
  id: 'demo_child_short_reflex_profile',
  version: 'demo_child_short_v1_2026_05',
  type: ReflexQuestionnaireType.demoChildShort,
  title: 'Reflexprofil Kurztest',
  scoring: const ReflexScoringDefinition(
    strongPercent: 100,
    elevatedPercent: 80,
    indicationPercent: 50,
  ),
  questions: [
    _demo('demo_delay', 11, ReflexQuestionModule.pregnancyBirth,
        'Wurde dein Kind zu früh geboren? (z. B. Frühchen)', [r.delay]),
    _demo('demo_flr', 51, ReflexQuestionModule.behaviorEmotion,
        'Ist dein Kind überdurchschnittlich ängstlich?', [r.flr, r.moro]),
    _demo('demo_moro', 60, ReflexQuestionModule.behaviorEmotion,
        'Ist dein Kind leicht ablenkbar?', [r.moro]),
    _demo('demo_spinal_galant', 39, ReflexQuestionModule.motorSkills,
        'Hat dein Kind einen schiefen Gang?', [r.spinalGalant]),
    _demo('demo_tlr', 85, ReflexQuestionModule.school,
        'Hat dein Kind Schwierigkeiten, von der Tafel abzuschreiben?', [r.tlr]),
    _demo(
        'demo_atnr',
        83,
        ReflexQuestionModule.drawingWriting,
        'Fällt es deinem Kind schwer, beim Schreiben die Linien einzuhalten?',
        [r.atnr]),
    _demo('demo_stnr', 35, ReflexQuestionModule.motorSkills,
        'Hat dein Kind das Krabbeln ausgelassen?', [r.stnr]),
    _demo(
        'demo_landau',
        45,
        ReflexQuestionModule.motorSkills,
        'Hat oder hatte dein Kind Probleme beim Schwimmenlernen, besonders beim Brustschwimmen?',
        [r.stnr, r.landau]),
    _demo('demo_babinski', 31, ReflexQuestionModule.posturePerception,
        'Ist dein Kind übermäßig kitzelig an den Füßen?', [r.babinski]),
    _demo('demo_babkin', 66, ReflexQuestionModule.speech,
        'Knirscht dein Kind mit den Zähnen?', [r.babkin]),
    _demo('demo_plantar', 41, ReflexQuestionModule.motorSkills,
        'Zieht dein Kind Strümpfe und Schuhe umständlich an?', [r.plantar]),
    _demo(
        'demo_palmar',
        75,
        ReflexQuestionModule.drawingWriting,
        'Drückt dein Kind den Stift beim Schreiben oder Malen sehr stark auf?',
        [r.palmar]),
    _demo(
        'demo_righting',
        77,
        ReflexQuestionModule.drawingWriting,
        'Ermüdet dein Kind sehr schnell beim Malen oder Schreiben?',
        [r.stnr, r.palmar, r.righting]),
    _demo(
        'demo_rooting_sucking',
        68,
        ReflexQuestionModule.speech,
        'Hat dein Kind einen übermäßig starken Speichelfluss?',
        [r.babkin, r.rootingSucking]),
  ],
);

const r = _ReflexRefs();

class _ReflexRefs {
  const _ReflexRefs();

  PrimitiveReflex get delay => PrimitiveReflex.delay;
  PrimitiveReflex get flr => PrimitiveReflex.flr;
  PrimitiveReflex get moro => PrimitiveReflex.moro;
  PrimitiveReflex get spinalGalant => PrimitiveReflex.spinalGalant;
  PrimitiveReflex get tlr => PrimitiveReflex.tlr;
  PrimitiveReflex get atnr => PrimitiveReflex.atnr;
  PrimitiveReflex get stnr => PrimitiveReflex.stnr;
  PrimitiveReflex get landau => PrimitiveReflex.landau;
  PrimitiveReflex get babinski => PrimitiveReflex.babinski;
  PrimitiveReflex get babkin => PrimitiveReflex.babkin;
  PrimitiveReflex get plantar => PrimitiveReflex.plantar;
  PrimitiveReflex get palmar => PrimitiveReflex.palmar;
  PrimitiveReflex get righting => PrimitiveReflex.righting;
  PrimitiveReflex get rootingSucking => PrimitiveReflex.rootingSucking;
}

ReflexQuestion _q(
  int number,
  ReflexQuestionModule module,
  String text, {
  List<PrimitiveReflex> reflexes = const [],
  String? helpText,
  String? trainerFlagLabel,
}) {
  return ReflexQuestion(
    id: _questionId(number),
    number: number,
    module: module,
    text: text,
    answerType: ReflexAnswerType.yesNoUnknown,
    reflexes: reflexes,
    helpText: helpText,
    trainerFlagLabel: trainerFlagLabel,
  );
}

ReflexQuestion _context(
  int number,
  ReflexQuestionModule module,
  String text, {
  ReflexAnswerType answerType = ReflexAnswerType.yesNoUnknown,
  String? followUpOf,
}) {
  return ReflexQuestion(
    id: _questionId(number),
    number: number,
    module: module,
    text: text,
    answerType: answerType,
    role: ReflexQuestionRole.context,
    followUpOf: followUpOf,
  );
}

ReflexQuestion _warning(
  int number,
  String text,
  String trainerFlagLabel, {
  List<PrimitiveReflex> reflexes = const [],
}) {
  return ReflexQuestion(
    id: _questionId(number),
    number: number,
    module: ReflexQuestionModule.other,
    text: text,
    answerType: ReflexAnswerType.yesNoUnknown,
    role:
        reflexes.isEmpty ? ReflexQuestionRole.safety : ReflexQuestionRole.score,
    reflexes: reflexes,
    warningRule: ReflexWarningRule.professionalClearanceRequired,
    trainerFlagLabel: trainerFlagLabel,
  );
}

ReflexQuestion _demo(
  String id,
  int sourceNumber,
  ReflexQuestionModule module,
  String text,
  List<PrimitiveReflex> reflexes,
) {
  return ReflexQuestion(
    id: id,
    number: sourceNumber,
    module: module,
    text: text,
    answerType: ReflexAnswerType.yesNoUnknown,
    reflexes: reflexes,
  );
}

String _questionId(int number) => 'q${number.toString().padLeft(3, '0')}';
